chore: deprecate run_jobby_... scripts
fixes #119

diff --git a/scripts/run_jobby_on_snakemake_log b/scripts/run_jobby_on_snakemake_log
--- a/scripts/run_jobby_on_snakemake_log
+++ b/scripts/run_jobby_on_snakemake_log
@@ -1,3 +1,8 @@
 #!/usr/bin/env bash
-snakemakelog=$1
-jobby $(grep --color=never "^Submitted .* with external jobid" $snakemakelog | awk '{{print $NF}}'  | sed "s/['.]//g" | sort | uniq | tr "\\n" " ") |cut -f2,3,18
+SCRIPT=$(basename ${BASH_SOURCE[0]})
+echo """ERROR: ${SCRIPT} is deprecated.
+Please use jobby instead. For usage information, run:
+
+    jobby --help
+""" >&2
+exit 1
